# Generated by Django 6.0.7 on 2026-07-29 07:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=1024)),
                ('status', models.CharField(blank=True, choices=[('added', 'Added'), ('modified', 'Modified'), ('removed', 'Removed'), ('renamed', 'Renamed')], max_length=10)),
                ('additions', models.PositiveIntegerField(blank=True, null=True)),
                ('deletions', models.PositiveIntegerField(blank=True, null=True)),
                ('patch', models.TextField(blank=True)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='integrations.commit')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('commit', 'filename'), name='unique_commit_file')],
            },
        ),
    ]
