# Generated by Django 6.0.7 on 2026-07-29 11:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_commitfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_mr_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('source_branch', models.CharField(blank=True, max_length=255)),
                ('target_branch', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('provider_state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('merged', 'Merged')], default='open', max_length=10)),
                ('provider_created_at', models.DateTimeField(blank=True, null=True)),
                ('provider_updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved (merged)'), ('rejected', 'Rejected'), ('closed', 'Closed without merging')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_requests', to='integrations.repository')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_merge_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-provider_created_at'],
                'constraints': [models.UniqueConstraint(fields=('repository', 'provider_mr_id'), name='unique_repo_merge_request')],
            },
        ),
    ]
