# Generated by Django 6.0.7 on 2026-08-11 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_mergerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['repository', 'authored_at'], name='commit_repo_authored_idx'),
        ),
    ]
